name: Check Arduino

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * TUE" # Run every Tuesday at 8 AM UTC
  workflow_dispatch:
  repository_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v2
        with:
          compliance: specification
          library-manager: update
          project-type: library